### ISSUE TITLE
display category?

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#1]
Not sure if it's possible (i.e., if we have the info), but can we play the category om top of each tile?
> BUITENLAND
> Zijn verhaal is bekend, maar de documentaire van Sinan Can overstijgt Housseins 'zoektocht'
> 
> Wanneer Houssein het mobiele nummer van zijn jongste zoon Ilyas belt, hoort hij een stem. 'Dit nummer is niet meer in gebruik.' Ilyas is dood. Omgekomen bij een bombardement op een IS-wapendepot in de buurt van Raqqa. 

That would help the reader understand in a fraction of a second what it's about, and it's also how it's done one other news sites.

**Comment by FeLoe** [comment]
Category is displayed on top of each article now - with colors (so one can clearly identify the categories at once).
