### ISSUE TITLE
News item page: lighter?

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#2]
Comparing https://3bij3.nl/detail/586 with https://www.nu.nl/sport-overig/5195186/mislukte-zoekactie-overboord-geslagen-britse-zeiler-volvo-ocean-race.html , I see that the latter has more space between paragraphs and between text and picture, which makes the layout lighter and nicer to read.

**Comment by FeLoe** [comment]
New layout, now with more space - still problematic that there are no paragraphs for some of the articles, but splitting into paragraphs automatically might not always make much sense... I will look into that, but I guess sometimes we just have a large block of text..
