### ISSUE TITLE
3x3 = 3x2

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#4]
On my laptop screen, I see exactly 3x2 stories. That's a bit onfortunate, because it privileges the articles in the two top rows. Not sure if feasible, but let's check whether we could fit it on one screen

**Comment by damian0604** [comment]
... for example, if we make the top bar a side bar, it could fit.

**Comment by FeLoe** [comment]
Now with sidebar and less text, so they should always fit on one screen (has to be tested on different laptops though...)
