### ISSUE TITLE
Template with picture too wide text

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#5]
On https://3bij3.nl/detail/616 , the text under the picture is very wide. The column should be less wide. I think this here https://www.nu.nl/sport-overig/5195186/mislukte-zoekactie-overboord-geslagen-britse-zeiler-volvo-ocean-race.html should be the maximum with for comfortable reading.

**Comment by FeLoe** [comment]
Layout changed..should not be an issue anymore
