### ISSUE TITLE
1 column layout instead of two columns?

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#6]
Here, https://3bij3.nl/detail/664 the column with is good. But maybe we should put it onder each other instead of next to each other? I think that's a bit more the ``modern'' way of doing it

**Comment by FeLoe** [comment]
Yes, also thought about it - however, for example here https://www.nu.nl/sport-overig/5195186/volvo-ocean-race-gaat-ervan-overboord-geslagen-zeiler-omgekomen.html?redirect=1 they have a lot of content around the article (ads etc) - if the text is only one column wide the page might seem a bit "naked"? But I can try and see how it looks..

**Comment by damian0604** [comment]
We could 'fill' the margin on the left with some sort of menu (links such as "Hoofdpagina"/ "Mail ons"/ ... )

**Comment by FeLoe** [comment]
The margin is now filled with a menu - I added a contact form and a FAQ (just questions that popped into my head, if anything else should be in there...and the dutch probably needs some checking :D ) and a link to the main page. And for the group with the customizable categories the selection dropdown is now part of the menu.

**Comment by FeLoe** [comment]
For checking out how the different groups work/look like: I created testing accounts (password same as name)
- tester7 for category selection
- tester or tester3 or  tester6  for past behavior
