### ISSUE TITLE
wild idea: reward users/gamification?

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#7]
I was thinking about how to motivate people to actually rate the articles (instead of just hitting the back-button of the browser).
Rating gives them an additonal possibility (i.e., refreshing the home page) but that's not transparent/clear to them. Maybe we could count how often they rate something (and then have a threshold as requirement for finishing the study, or -- more fun -- give some reward when they rated stuff ...)

(not something to fix right now, but maybe an idea for in the long run)

**Comment by FeLoe** [comment]
There is now a page showing the points for each category + the overall statistics (min, avg, max) of all other users. The website should now also work on tablets and mobile phones with different layouts and weird-looking articles can be reported. Lastly, the page can be shared with others (+ getting points if the invited people use the page) with a link or via Facebook or Twitter.
