### ISSUE TITLE
layout error Firefox MacOs

### ISSUE THREAD

**Issue by damian0604** [FeLoe/3bij3#8]
![afbeelding](https://user-images.githubusercontent.com/5979167/38472198-8702bfce-3b7c-11e8-9f89-36658384e63a.png)

(Safari looks good, though)

**Comment by FeLoe** [comment]
Will loo into that...and for all devices that used the website earlier the cache should be emptied (could cause problems otherwise..)

**Comment by damian0604** [comment]
That was the issue indeed!
